[project]
name = "conference-maker"
version = "0.1.0"
description = "A conference making tools for the Shifters"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "numpy>=2.2.5",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "python-pptx>=1.0.2",
    "pywin32>=310",
    "waitress>=3.0.2",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.13.0",
    "mypy>=1.16.0"
]

[tool.mypy]
ignore_missing_imports = true
