# Generated by Django 5.1 on 2024-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencemodule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
