# Generated by Django 5.1 on 2024-09-05 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_conferencemodule_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceModuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_category_importance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('conference_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.conferencemodule')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.tag')),
            ],
        ),
        migrations.AddField(
            model_name='conferencemodule',
            name='tags',
            field=models.ManyToManyField(through='maker.ConferenceModuleTag', to='maker.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maker.tagcategory'),
        ),
    ]
